[tool.black]
line-length = 100
target-version = ["py38"]

[tool.isort]
src_paths = [
    "tools",
    "zulip",
    "zulip/integrations/zephyr",
    "zulip_bots",
    "zulip_botserver",
]
profile = "black"
line_length = 100
